name: resq
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.3
  geolocator: ^7.7.0
  permission_handler: ^8.1.6
  geocoding: ^2.0.0
  logging: ^1.0.1
  url_launcher: ^6.0.10
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.2
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.png
    - .env

# 아이콘 설정
flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

# 스플래시 스크린 설정
flutter_native_splash:
  color: "#606060"
  image: "assets/splash.png"
  fullscreen: true
  android_12: # 안드로이드 12 이상은 별도 코드가 필요
    image: "assets/splash.png"
  image_android: "assets/splash.png"