// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMRz6H-w3RR172jDxqNEn0rGw-6fxmO2U',
    appId: '1:485828839420:web:d7127127a5d34aeedad479',
    messagingSenderId: '485828839420',
    projectId: 'aiways1',
    authDomain: 'aiways1.firebaseapp.com',
    storageBucket: 'aiways1.appspot.com',
    measurementId: 'G-ZR46QQ4TCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpuU_5xQkWdtOvmw5tjeQSR6IUS7YYJG4',
    appId: '1:485828839420:android:a23a39b48e8da40bdad479',
    messagingSenderId: '485828839420',
    projectId: 'aiways1',
    storageBucket: 'aiways1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-9zJEcZDWdaoo1mA98kIwVG2BHtafn0A',
    appId: '1:485828839420:ios:777f33c74a84397cdad479',
    messagingSenderId: '485828839420',
    projectId: 'aiways1',
    storageBucket: 'aiways1.appspot.com',
    iosBundleId: 'com.example.aiways',
  );
}
